In [0]:
dp1 = {'partno':100,'maxtemp':35,'mintemp':12,'maxvibration':12,'aspirity':.32}
dp2 = {'partno':101,'maxtemp':46,'mintemp':35,'maxvibration':21,'aspirity':.34}
dp3 = {'partno':130,'maxtemp':56,'mintemp':46,'maxvibration':3412,'aspirity':12.42}
dp4 = {'partno':131,'maxtemp':58,'mintemp':48,'maxvibration':3542,'aspirity':13.43}


In [0]:
def predict(dp):
  if dp['maxvibration'] > 100:
    return 13
  else:
    return 0.33

In [3]:
predict(dp1)

0.33

In [4]:
print (predict(dp2))
print (predict(dp3))
print (predict(dp4))

0.33
13
13


In [0]:
### with linear regression model 

w1=0.33
w2=0
w3=0
w4=13/3412.0
def mlpredict(dp):
  return w1+w2*dp['maxtemp']+w3*dp['mintemp']+w4*dp['maxvibration']

In [6]:
mlpredict(dp1)

0.37572098475967175

In [7]:
print (mlpredict(dp1))
print (mlpredict(dp2))
print (mlpredict(dp3))

0.37572098475967175
0.4100117233294256
13.33


In [0]:
x0=1

In [0]:
### binary classification

dp1 = {'partno':100,'maxtemp':35,'mintemp':12,'maxvibration':12,'broken':0}
dp2 = {'partno':101,'maxtemp':46,'mintemp':35,'maxvibration':21,'broken':0}
dp3 = {'partno':130,'maxtemp':56,'mintemp':46,'maxvibration':3412,'broken':1}
dp4 = {'partno':131,'maxtemp':58,'mintemp':48,'maxvibration':3542,'broken':1}


In [0]:
def predict(dp):
  if dp['maxvibration'] > 100:
    return 1
  else:
    return 0

In [11]:
print (predict(dp1))
print (predict(dp2))
print (predict(dp3))
print (predict(dp4))

0
0
1
1


In [0]:
#### using in the logistic regression
## fist make a sigmoid function
import math

def sigmoid(x):
  return 1/(1+math.exp(-x))

In [0]:
## with sigmoid function

def mlpredict(dp):
  return 1 if sigmoid(w1+w2*dp['maxtemp']+w3*dp['mintemp']+w4*dp['maxvibration']) > .7 else 0

In [14]:
print (mlpredict(dp1))
print (mlpredict(dp2))
print (mlpredict(dp3))
print (mlpredict(dp4))

0
0
1
1


In [0]:
## if you use a threshhold in the logistic regression you can convert it 
## to  a binary classifier

In [0]:
## single perceptron
# if you put a unit step function in front a regression a model you got a 
## perceptron 

In [21]:
##feed forward nural network


dp1 = {'partno':100,'maxtemp':35,'mintemp':12,'maxvibration':12,'aspirity':.32}
dp2 = {'partno':101,'maxtemp':46,'mintemp':35,'maxvibration':21,'aspirity':.34}
dp3 = {'partno':130,'maxtemp':56,'mintemp':46,'maxvibration':3412,'aspirity':12.42}
dp4 = {'partno':131,'maxtemp':58,'mintemp':48,'maxvibration':3542,'aspirity':13.43}





for x,y in dp1.items():
  print (x,y)

partno 100
maxtemp 35
mintemp 12
maxvibration 12
aspirity 0.32


In [0]:
x1 = [v for k,v in dp1.items()]

In [0]:
## there are two value in the dict we take the second one

In [0]:
# we will get rid of the partno and the aspirity and add bias
import numpy as np
x1 = np.array([1]+ x1[1:-1])

In [0]:
x1 = np.array([1]+ [v for k,v in dp1.items()] [1:-1])
x2 = np.array([1]+ [v for k,v in dp2.items()] [1:-1])
x3 = np.array([1]+ [v for k,v in dp3.items()] [1:-1])
x4 = np.array([1]+ [v for k,v in dp4.items()] [1:-1])

In [0]:
w1_layer=np.random.rand(4)

In [0]:
def nuron(x):
  return sigmoid(x.dot(w1_layer))

In [35]:
print (nuron(x1))
print (nuron(x2))
print (nuron(x3))
print (nuron(x4))

1.0
1.0
1.0
1.0


In [0]:
## we can add multiplem value in our perceptron

In [0]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [0]:
x= np.array([x1,x2,x3,x4])

In [40]:
x

array([[   1,   35,   12,   12],
       [   1,   46,   35,   21],
       [   1,   56,   46, 3412],
       [   1,   58,   48, 3542]])

In [0]:
# now our value is a matrix so wight have to be a matrix
w_layer1 = np.random.rand(4,4)

In [46]:
w_layer1

array([[0.87047239, 0.19596546, 0.18895845, 0.37416275],
       [0.81307834, 0.31249974, 0.68305609, 0.19544718],
       [0.45218899, 0.85327341, 0.41949466, 0.00970496],
       [0.07875538, 0.76821246, 0.75121962, 0.8423762 ]])

In [0]:
w_layer1 = np.random.rand(4,4)
def layer1(x):
  return sigmoid(x.dot(w_layer1))

In [51]:
layer1(x)

array([[0.99999999, 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ]])

In [0]:
w_layer2 = np.random.rand(4,4)
def layer2(x):
  return sigmoid(x.dot(w_layer2))

In [54]:
layer2(layer1(x))

array([[0.86902308, 0.90165052, 0.83019443, 0.84807553],
       [0.86902308, 0.90165052, 0.83019443, 0.84807553],
       [0.86902308, 0.90165052, 0.83019443, 0.84807553],
       [0.86902308, 0.90165052, 0.83019443, 0.84807553]])

## convolutional nural network

In [0]:
## why we dont solve image classificaion in feed forward nural network??
##  cause we need tousands of wight for that

In [0]:
#LSTM

# LSTM

In [0]:
x=np.array([1,2,3])

In [0]:
y=np.array([4,5,6])

In [62]:
x.dot(y)

32